---
title: "code 2"
author: "jingxuan song"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
#install.packages("kernlab")
suppressPackageStartupMessages({
  library(tidyverse)
  library(palmerpenguins)
  library(tidymodels)
})
danish <-read_csv("Danish.csv",show_col_types = FALSE)
danish$emotion = as.factor(danish$emotion)
danish = subset(danish,select = -c(nationality,ID))
# Take a peek into the data
glimpse(danish)
```


```{r}
#install.packages("devtools")
devtools::install_github("ropensci/skimr")
library(skimr)
# Do some summary statistics
danish %>% 
  skim()
```

```{r}
danish <- danish %>% 
  drop_na()

danish %>% 
  anyNA()
```

```{r}
#does not work as id & other numeric features odes not fit in one plot
#install.packages("paletteer")
library(paletteer)
# Pivot data to a long format
danish_long <- danish %>% 
  pivot_longer(c(duration_noSilence,voiced_noSilence,HNRVoiced_mean,f1_freq_mean), names_to = "predictors", values_to = "values")

# Make box plots
theme_set(theme_light())
danish_long %>%
  ggplot(mapping = aes(x = emotion, y = values, fill = predictors)) +
  geom_boxplot() +
  facet_wrap(~predictors, scales = "free") +
  scale_fill_paletteer_d("nbapalettes::supersonics_holiday") +
  theme(legend.position = "none")
```

```{r}
# For reproducibility
set.seed(2056)

# Split data 70%-30% into training set and test set
danish_split <- danish %>% 
  initial_split(prop = 0.70, strata = emotion)

# Extract data in each split
danish_train <- training(danish_split)
danish_test <- testing(danish_split)

# Print the number of observations in each split
cat("Training cases: ", nrow(danish_train), "\n",
    "Test cases: ", nrow(danish_test), sep = "")

```

```{r}
multireg_spec <- multinom_reg(penalty = 1) %>% 
  set_engine("nnet") %>% 
  set_mode("classification")

# Train a multinomial regression model without any preprocessing
set.seed(2056)
multireg_fit <- multireg_spec %>% 
  fit(emotion ~ ., data = danish_train)

# Print the model
multireg_fit
```

```{r}
danish_results <- danish_test %>% select(emotion) %>% 
  bind_cols(multireg_fit %>% 
              predict(new_data = danish_test)) %>% 
  bind_cols(multireg_fit %>% 
              predict(new_data = danish_test, type = "prob"))

# Print predictions
danish_results %>% 
  slice_head(n = 5)

```

```{r}
# Confusion matrix
danish_results %>% 
  conf_mat(emotion, .pred_class)
```

```{r}
update_geom_defaults(geom = "tile", new = list(color = "black", alpha = 0.7))
# Visualize confusion matrix
danish_results %>% 
  conf_mat(emotion, .pred_class) %>% 
  autoplot(type = "heatmap")
```

```{r}
# Statistical summaries for the confusion matrix
conf_mat(data = danish_results, truth = emotion, estimate = .pred_class) %>% 
  summary()
```

```{r}
# Make an ROC_CURVE
#install.packages("tidyverse")
library(tidyverse)
danish_results %>% 
  roc_curve(emotion, .pred_Happy, .pred_Neutral, .pred_Sad) %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity, color = .level)) +
  geom_abline(lty = 2, color = "gray80", linewidth = 0.9) +
  geom_path(show.legend = T, alpha = 0.6, linewidth = 1.2) +
  coord_equal()
```

```{r}
# Create a model specification
svm_spec <- svm_rbf(mode = "classification", engine = "kernlab",
            cost = tune(), rbf_sigma = tune())


# Create a workflow that encapsulates a recipe and a model
svm_wflow <- recipe(emotion ~ ., data = danish_train) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  workflow(svm_spec)

# Print out workflow
svm_wflow
```

```{r}
set.seed(2056)
# Create a regular grid of six values for each tuning parameter
svm_grid <- grid_regular(parameters(svm_spec), levels = 6)

# Print out some parameters in your grid
svm_grid %>% 
  slice_head(n = 10)

```

```{r}
set.seed(2056)
# Bootstrap resampling
danish_bs <- bootstraps(danish_train, times = 10)

danish_bs


```

```{r}
doParallel::registerDoParallel()

# Model tuning via a grid search
set.seed(2056)
svm_res <- tune_grid(
  object = svm_wflow,
  resamples = danish_bs,
  grid = svm_grid
)
```

```{r}
# Obtain performance metrics
svm_res %>% 
  collect_metrics() %>% 
  slice_head(n = 7)
```

```{r}
# Visualize the tuning metrics
svm_res %>% 
  collect_metrics() %>% 
  mutate(rbf_sigma = factor(rbf_sigma)) %>% 
  ggplot(mapping = aes(x = cost, y = mean, color = rbf_sigma)) +
  geom_line(size = 1.5, alpha = 0.7) +
  geom_point(size = 2) +
  facet_wrap(~.metric, scales = "free", nrow = 2) +
  scale_x_log10(labels = scales::label_number()) +
  scale_color_viridis_d(option = "viridis", begin = .1)


```

```{r}
# Show best submodel 
svm_res %>% 
  show_best("accuracy")
```

```{r}
# Select best model hyperparameters
best_svm <- svm_res %>% 
  select_best("accuracy")

best_svm

```

```{r}
# Finalize the workflow
final_wflow <- svm_wflow %>% 
  finalize_workflow(best_svm)

final_wflow
```

```{r}
# The last fit
final_fit <- last_fit(object = final_wflow, split = danish_split)

# Collect metrics
final_fit %>% 
  collect_metrics()

```

```{r}
# Collect predictions and make a confusion matrix
final_fit %>% 
  collect_predictions() %>% 
  conf_mat(truth = emotion, estimate = .pred_class)

```

```{r}
# Extract the trained workflow
danish_svm_model <- final_fit %>% 
  extract_workflow()

# Save the workflow
library(here)
saveRDS(danish_svm_model, "danish_svm_model.rds")
```

```{r}
chinese <-read_csv("Chinese.csv",show_col_types = FALSE)
chinese = subset(chinese,select = -c(nationality,ID))
chinese$emotion = as.factor(chinese$emotion)
```
```{r}
loaded_psvm_model <- readRDS("danish_svm_model.rds") 
```

```{r}
chinese <- chinese %>% 
  drop_na()

chinese %>% 
  anyNA()
```


```{r}
chinese_results <- chinese%>% select(emotion) %>% 
  bind_cols(loaded_psvm_model %>% 
              predict(new_data = chinese)) %>%
  bind_cols(loaded_psvm_model %>% 
              predict(new_data = chinese, type = "prob"))

# Print predictions
chinese_results %>% 
  slice_head(n = 5)

```

```{r}
# Confusion matrix
chinese_results %>% 
  conf_mat(emotion, .pred_class)
```

```{r}
update_geom_defaults(geom = "tile", new = list(color = "black", alpha = 0.7))
# Visualize confusion matrix
chinese_results %>% 
  conf_mat(emotion, .pred_class) %>% 
  autoplot(type = "heatmap")
```

```{r}
#Statistical summaries for the confusion matrix
conf_mat(data = chinese_results, truth = emotion, estimate = .pred_class) %>% 
  summary()

```

```{r}
# Make an ROC_CURVE
#install.packages("tidyverse")
library(tidyverse)
chinese_results %>% 
  roc_curve(emotion, .pred_Happy, .pred_Neutral, .pred_Sad) %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity, color = .level)) +
  geom_abline(lty = 2, color = "gray80", linewidth = 0.9) +
  geom_path(show.legend = T, alpha = 0.6, linewidth = 1.2) +
  coord_equal()
```

```{r}
spanish <-read_csv("Spanish.csv")
spanish = subset(spanish,select = -c(nationality,ID))
spanish$emotion = as.factor(spanish$emotion)
```

```{r}
loaded_psvm_model <- readRDS("danish_svm_model.rds") 
```

```{r}
spanish <- spanish %>% 
  drop_na()

spanish %>% 
  anyNA()
```


```{r}
spanish_results <- spanish%>% select(emotion) %>% 
  bind_cols(loaded_psvm_model %>% 
              predict(new_data = spanish)) %>%
  bind_cols(loaded_psvm_model %>% 
              predict(new_data = spanish, type = "prob"))

# Print predictions
spanish_results %>% 
  slice_head(n = 5)

```

```{r}
# Confusion matrix
spanish_results %>% 
  conf_mat(emotion, .pred_class)
```

```{r}
update_geom_defaults(geom = "tile", new = list(color = "black", alpha = 0.7))
# Visualize confusion matrix
spanish_results %>% 
  conf_mat(emotion, .pred_class) %>% 
  autoplot(type = "heatmap")
```

```{r}
#Statistical summaries for the confusion matrix
conf_mat(data = spanish_results, truth = emotion, estimate = .pred_class) %>% 
  summary()

```

```{r}
# Make an ROC_CURVE
#install.packages("tidyverse")
library(tidyverse)
spanish_results %>% 
  roc_curve(emotion, .pred_Happy, .pred_Neutral, .pred_Sad) %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity, color = .level)) +
  geom_abline(lty = 2, color = "gray80", linewidth = 0.9) +
  geom_path(show.legend = T, alpha = 0.6, linewidth = 1.2) +
  coord_equal()
```

```{r}
english <-read_csv("english.csv")
english = subset(english,select = -c(nationality,ID))
english$emotion = as.factor(english$emotion)
```

```{r}
loaded_psvm_model <- readRDS("danish_svm_model.rds") 
```

```{r}
english <- english %>% 
  drop_na()

english %>% 
  anyNA()
```


```{r}
english_results <- english%>% select(emotion) %>% 
  bind_cols(loaded_psvm_model %>% 
              predict(new_data = english)) %>%
  bind_cols(loaded_psvm_model %>% 
              predict(new_data = english, type = "prob"))

# Print predictions
english_results %>% 
  slice_head(n = 5)

```

```{r}
# Confusion matrix
english_results %>% 
  conf_mat(emotion, .pred_class)
```

```{r}
update_geom_defaults(geom = "tile", new = list(color = "black", alpha = 0.7))
# Visualize confusion matrix
english_results %>% 
  conf_mat(emotion, .pred_class) %>% 
  autoplot(type = "heatmap")
```

```{r}
#Statistical summaries for the confusion matrix
conf_mat(data = english_results, truth = emotion, estimate = .pred_class) %>% 
  summary()

```

```{r}
# Make an ROC_CURVE
#install.packages("tidyverse")
library(tidyverse)
english_results %>% 
  roc_curve(emotion, .pred_Happy, .pred_Neutral, .pred_Sad) %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity, color = .level)) +
  geom_abline(lty = 2, color = "gray80", linewidth = 0.9) +
  geom_path(show.legend = T, alpha = 0.6, linewidth = 1.2) +
  coord_equal()
```
