---
title: 'code3'
author: "jingxuan song"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(palmerpenguins)
  library(tidymodels)
})
```


```{r}
chinese <-read_csv("Chinese.csv",show_col_types = FALSE)
chinese = subset(chinese,select = -c(nationality,ID))
chinese$emotion = as.factor(chinese$emotion)
```

```{r}
chinese <- chinese %>% 
  drop_na()

chinese %>% 
  anyNA()
```



```{r}
#install.packages("caret")
library(caret)
```

```{r}
set.seed(2056)

# Split data 70%-30% into training set and test set
chinese_split <- chinese %>% 
  initial_split(prop = 0.70, strata = emotion)

# Extract data in each split
chinese_train <- training(chinese_split)
chinese_test <- testing(chinese_split)
dim(chinese_train)
dim(chinese_test)
```
```{r}
summary(chinese)

```

```{r}
trctrl <- trainControl(method = "repeatedcv", number = 5,repeats = 10)
set.seed(3333)
knn_fit <- train(emotion ~., data = chinese_train, method = "knn",
 trControl=trctrl,
 preProcess = c("center", "scale"),
 tuneLength = 10)
```

```{r}
knn_fit
```
```{r}
plot(knn_fit)
```
```{r}
test_pred <- predict(knn_fit, newdata = chinese_test)
test_pred
```

```{r}
confusionMatrix(test_pred, chinese_test$emotion)

```